# Generated by Django 4.2.5 on 2025-01-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
