# Generated by Django 4.2.5 on 2025-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_accountdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdetail",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="accountdetail",
            name="status",
            field=models.CharField(
                choices=[("0", "Pending"), ("1", "Success"), ("2", "Failed")],
                default="0",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("0", "Pending"), ("1", "Success"), ("2", "Failed")],
                default="0",
                max_length=20,
            ),
        ),
    ]
