# Generated by Django 4.2.5 on 2025-01-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_accountdetail_amount_accountdetail_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("0", "Deposit"), ("1", "Withdrawal")], max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Pending"), ("1", "Success"), ("2", "Failed")],
                        default="0",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.accountdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transection",
                "verbose_name_plural": "Transections",
            },
        ),
    ]
