# Generated by Django 4.2.5 on 2025-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Deposit", "Deposit"), ("Withdrawal", "Withdrawal")],
                max_length=50,
            ),
        ),
    ]
