# Generated by Django 4.2.5 on 2025-03-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_transaction_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
