# Generated by Django 4.2.5 on 2025-04-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_transaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountdetail",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="accountdetail",
            name="status",
        ),
    ]
