# Generated by Django 4.2.5 on 2025-04-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_remove_accountdetail_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdetail",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stripe_payment_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stripe_payment_link_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
