# Generated by Django 4.2.5 on 2025-05-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_accountdetail_stripe_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
