# Generated by Django 4.2.5 on 2025-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_transaction_invoice_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdetail",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
