# Generated by Django 4.2.5 on 2025-06-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0064_remove_bookedappointment_start_datetime_utc_and_more"),
        ("payments", "0011_accountdetail_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.bookedappointment",
            ),
        ),
    ]
