# Generated by Django 4.2.5 on 2024-12-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Patient", "Patient"),
                    ("Doctor", "Doctor"),
                    ("SuperAdmin", "Super Admin"),
                ],
                default="Patient",
                max_length=20,
            ),
        ),
    ]
