# Generated by Django 4.2.5 on 2024-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_licenses_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="licenses_certificate",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="media_digest",
            field=models.TextField(blank=True, null=True),
        ),
    ]
