# Generated by Django 4.2.5 on 2024-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_licenses_certificate_user_media_digest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfile",
            old_name="licenses_certificate",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="user",
            name="licenses_certificate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="media_digest",
        ),
        migrations.RemoveField(
            model_name="userfile",
            name="media_digest",
        ),
        migrations.AddField(
            model_name="userfile",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Certificate", "Certificate"), ("Media", "Media")],
                max_length=20,
                null=True,
            ),
        ),
    ]
