# Generated by Django 4.2.5 on 2024-12-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_verified_user_terms_and_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
