# Generated by Django 4.2.5 on 2025-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_education_user_alter_education_school_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_date",
        ),
        migrations.AddField(
            model_name="education",
            name="end_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
