# Generated by Django 4.2.5 on 2025-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_education_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="media",
        ),
        migrations.RemoveField(
            model_name="education",
            name="skills",
        ),
        migrations.AddField(
            model_name="education",
            name="media",
            field=models.ImageField(
                blank=True, null=True, upload_to="education_media/"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
