# Generated by Django 4.2.5 on 2025-02-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_otp_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_created_at",
        ),
    ]
