# Generated by Django 4.2.5 on 2025-02-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="temp_password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Patient", "Patient"),
                    ("Doctor", "Doctor"),
                    ("Clinic", "Clinic"),
                    ("SuperAdmin", "Super Admin"),
                ],
                default="Patient",
                max_length=20,
            ),
        ),
    ]
