# Generated by Django 4.2.5 on 2025-02-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinicreview_language_servicesprovided_and_more"),
        ("users", "0013_user_last_activity_user_temp_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="work_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_work",
                to="clinics.clinic",
            ),
        ),
    ]
