# Generated by Django 4.2.5 on 2025-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_remove_clinic_languages"),
        ("users", "0015_alter_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="languages",
        ),
        migrations.AddField(
            model_name="user",
            name="languages",
            field=models.ManyToManyField(to="clinics.language"),
        ),
    ]
