# Generated by Django 4.2.5 on 2025-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_user_languages_user_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="reviews",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
