# Generated by Django 4.2.5 on 2025-02-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_alter_clinic_administrator_email_and_more"),
        ("users", "0017_user_rating_user_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="expertise",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="languages",
            field=models.ManyToManyField(blank=True, to="clinics.language"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, default="", max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="professional_stat",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="residence",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="reviews",
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="temp_password",
            field=models.CharField(blank=True, default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="working_time",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
