# Generated by Django 4.2.5 on 2025-02-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_user_bio_alter_user_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="end_month",
        ),
        migrations.RemoveField(
            model_name="education",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_month",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_year",
        ),
        migrations.AddField(
            model_name="education",
            name="end_month_year",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="education",
            name="start_month_year",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
