# Generated by Django 4.2.5 on 2025-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_remove_education_end_month_remove_education_end_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_methods",
            field=models.ManyToManyField(blank=True, to="users.twofactormethod"),
        ),
    ]
