# Generated by Django 4.2.5 on 2025-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_twofactormethod_user_two_factor_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="skills",
        ),
        migrations.AddField(
            model_name="education",
            name="skills",
            field=models.ManyToManyField(blank=True, default="", to="users.skill"),
        ),
    ]
