# Generated by Django 4.2.5 on 2025-02-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="media",
        ),
        migrations.AddField(
            model_name="media",
            name="education",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.education",
            ),
        ),
    ]
