# Generated by Django 4.2.5 on 2025-03-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_remove_education_media_media_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="education",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="users.education",
            ),
        ),
    ]
