# Generated by Django 4.2.5 on 2025-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_token",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
