# Generated by Django 4.2.5 on 2025-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_deviceaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agora_channel_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
