# Generated by Django 4.2.5 on 2025-04-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_user_agora_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agoraReceiverUserUid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
