# Generated by Django 4.2.5 on 2025-04-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_user_agorareceiveruseruid"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceaccess",
            name="active_sessions",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
