# Generated by Django 4.2.5 on 2025-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_deviceaccess_active_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(default="", max_length=10),
        ),
    ]
