# Generated by Django 4.2.5 on 2025-04-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_remove_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                default="", help_text="Currency code", max_length=10
            ),
        ),
    ]
