# Generated by Django 4.2.5 on 2025-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_user_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_doctor_switched",
            field=models.BooleanField(default=False),
        ),
    ]
