# Generated by Django 4.2.5 on 2025-04-30 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_user_is_doctor_switched"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
