# Generated by Django 4.2.5 on 2025-05-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="UIDSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=10)),
                ("date", models.CharField(max_length=8)),
                ("counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("prefix", "date")},
            },
        ),
    ]
