# Generated by Django 4.2.5 on 2025-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_applanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="acknowledge",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="code_of_conduct",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_disclaimer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
