# Generated by Django 4.2.5 on 2025-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_user_acknowledge_user_code_of_conduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Patient", "Patient"),
                    ("Doctor", "Doctor"),
                    ("Clinic", "Clinic"),
                    ("Admin", "Admin"),
                    ("SuperAdmin", "Super Admin"),
                ],
                default="Patient",
                max_length=20,
            ),
        ),
    ]
