# Generated by Django 4.2.5 on 2025-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                default="USD", help_text="Currency code", max_length=10
            ),
        ),
    ]
