trigger:
  branches:
    include:
      - development  # Only trigger on the development branch

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - deployment: DeployToVM
    displayName: web
    workspace:
      clean: all
    environment:
      name: 'staging' 
      resourceType: VirtualMachine
      resourceName: 'Healthcare-backend' 
    strategy:
        runOnce:
          preDeploy:
            steps:
            - checkout: self 
              workspaceRepo:  true
            -  script: |
                  mkdir /home/azureuser/$(Build.BuildId)
                  mv $(Build.SourcesDirectory)/*  /home/azureuser/$(Build.BuildId)
          deploy:
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                workingDirectory: /home/azureuser/testing
                script: |
                    cp .env /home/azureuser/$(Build.BuildId)/
              displayName: 'copy .env to new folder'
            - task: Bash@3
              inputs:
                targetType: 'inline'
                workingDirectory: /home/azureuser/$(Build.BuildId)
                script: |
                  if [ ! -d "venv" ]; then
                    python3 -m venv venv
                  fi
                  python3 -m venv venv
                  source venv/bin/activate
                  pip3 install django gunicorn psycopg2-binary
                  pip3 install -r requirements.txt
              displayName: 'Install dependencies and Run Migration scripts'
                  # Step 2: Make migrations (separate step)
            - task: Bash@3
              inputs:
                targetType: 'inline'
                workingDirectory: /home/azureuser/$(Build.BuildId)
                script: |
                  # Make migrations
                   source venv/bin/activate
                   python3 manage.py migrate --fake

              displayName: 'Make Migrations'
              
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  cp -r --no-dereference --preserve=links  /home/azureuser/$(Build.BuildId) /home/azureuser/stable
                  systemctl restart gunicorn.socket gunicorn.service
              displayName: 'restarting'