trigger:
  branches:
    include:
      - development  # Only trigger on the development branch

pool:
  vmImage: 'ubuntu-latest'

jobs:
  # Job 1: Build and Install Dependencies
  - job: BuildAndDeploy
    steps:
      # Step 1: Checkout code
      - checkout: self
      
      # Step 2: Set up Python
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      # Step 3: Install dependencies
      - script: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        displayName: 'Install dependencies'
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: $(System.DefaultWorkingDirectory)
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifact: drop
      
  # Job 2: Deployment to Virtual Machine
  - deployment: DeployToVM
    environment:
      name: 'staging' 
      resourceType: VirtualMachine
      resourceName: 'Healthcare-backend'
    strategy:
        runOnce:
          preDeploy:
            steps:
            - download: current
              artifact: drop
            - script: |
                cp $(Pipeline.Workspace)/drop/*.zip  ~/healthcaredir
          deploy:
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  cd ~/healthcaredir
                  # Make migrations, apply them, and restart the server
                  ls 