# Generated by Django 4.2.5 on 2024-12-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("services_provided", models.TextField(blank=True, null=True)),
                ("licenses_certificate", models.TextField(blank=True, null=True)),
                ("languages", models.TextField(blank=True, null=True)),
                ("working_time", models.TextField(blank=True, null=True)),
                (
                    "administrator_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "administrator_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
    ]
