# Generated by Django 4.2.5 on 2025-02-08 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0022_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("recommend", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ServicesProvided",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name="clinic",
            old_name="phone_number",
            new_name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="email",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="name",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="password",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="working_time",
        ),
        migrations.AddField(
            model_name="clinic",
            name="clinic_logo",
            field=models.ImageField(blank=True, null=True, upload_to="clinic_logo"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="clinic_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Public"), (1, "Private"), (2, "Specialty")], default=0
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="clinic",
            name="license_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="optional_information",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="organisation_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="public_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="languages",
        ),
        migrations.AlterField(
            model_name="clinic",
            name="licenses_certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificate"),
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="services_provided",
        ),
        migrations.CreateModel(
            name="ClinicReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_replies",
                        to="clinics.clinicreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="clinicreview",
            name="clinic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="clinics.clinic",
            ),
        ),
        migrations.AddField(
            model_name="clinicreview",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="doctors.doctor",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="languages",
            field=models.ManyToManyField(to="clinics.language"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="services_provided",
            field=models.ManyToManyField(to="clinics.servicesprovided"),
        ),
    ]
