# Generated by Django 4.2.5 on 2025-02-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinicreview_language_servicesprovided_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="languages",
        ),
    ]
