# Generated by Django 4.2.5 on 2025-02-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_remove_clinic_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="administrator_email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinic",
            name="administrator_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinic",
            name="clinic_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Public"), (1, "Private"), (2, "Specialty")],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinic",
            name="optional_information",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinic",
            name="organisation_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinic",
            name="public_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinic",
            name="services_provided",
            field=models.ManyToManyField(blank=True, to="clinics.servicesprovided"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="website",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinicreview",
            name="content",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinicreview",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
