# Generated by Django 4.2.5 on 2025-02-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_alter_clinic_administrator_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="administrator_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="administrator_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="license_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="optional_information",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="organisation_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="public_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="clinicreview",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="clinicreview",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clinicreview",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
