# Generated by Django 4.2.5 on 2025-04-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0056_bookedappointment_amount_doctorwallet"),
        ("clinics", "0005_alter_clinic_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherClinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
            ],
        ),
    ]
