# Generated by Django 4.2.5 on 2025-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_call", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agoratoken",
            name="record_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
