# Generated by Django 4.2.5 on 2025-07-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0067_bookedappointment_charge_id_and_more"),
        ("video_call", "0004_meetingroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCallTimeTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_start_time", models.DateTimeField(blank=True, null=True)),
                ("doctor_end_time", models.DateTimeField(blank=True, null=True)),
                ("patient_start_time", models.DateTimeField(blank=True, null=True)),
                ("patient_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.bookedappointment",
                    ),
                ),
            ],
        ),
    ]
