"""
Django settings for health_care_backend project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd84*5d9^_qv--%8in$l1&2$%(rbbfywi=zfc9v5jv!w(r%5x#x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', '209.38.123.166', '20.0.160.6']

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'social_django',
    'authify',
    'users',
    'patients',
    'doctors',
    'clinics',
    'appointments',
    'payments',
    'consultations',
    'reviews',
    'dashboard',
    'chat',
    'MasterPanel',              # Admin Api
    'notifications',
    'video_call',
    'django_celery_beat',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',  # For Google Login
    'social_core.backends.apple.AppleIdAuth',  # For Apple Login
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

# Google OAuth2 credentials
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')

# Apple ID credentials
SOCIAL_AUTH_APPLE_CLIENT_ID = os.getenv('APPLE_CLIENT_ID')
SOCIAL_AUTH_APPLE_TEAM_ID = os.getenv('APPLE_TEAM_ID')
SOCIAL_AUTH_APPLE_KEY_ID = os.getenv('APPLE_KEY_ID')
SOCIAL_AUTH_APPLE_SECRET = os.getenv('APPLE_PRIVATE_KEY')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'health_care_backend.middleware.ActivityMiddleware'
]

ROOT_URLCONF = 'health_care_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'health_care_backend.wsgi.application'
ASGI_APPLICATION = 'health_care_backend.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     }
# }


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# media files
DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
AZURE_URL_EXPIRATION_SECS= 86400
AZURE_OVERWRITE_FILES = False
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER = os.getenv("AZURE_CONTAINER")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'users.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
SENDGRID_FROM_EMAIL = os.getenv('SENDGRID_FROM_EMAIL')
SENDGRID_TEMPLATE_ID = os.getenv('SENDGRID_TEMPLATE_ID')
REPORT_ADMIN_EMAIL = os.getenv('REPORT_ADMIN_EMAIL')

# Stripe authentication credentials
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')

# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

# Implementing Logfile settings
BASE_LOG_DIR = os.path.join(BASE_DIR, 'logs')

if not os.path.exists(BASE_LOG_DIR):
    os.makedirs(BASE_LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'appointments': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'appointments.log'),
            'formatter': 'verbose',
        },
        'authify': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'authify.log'),
            'formatter': 'verbose',
        },
        'clinics': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'clinics.log'),
            'formatter': 'verbose',
        },
        'consultations': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'consultations.log'),
            'formatter': 'verbose',
        },
        'dashboard': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'dashboard.log'),
            'formatter': 'verbose',
        },
        'doctors': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'doctors.log'),
            'formatter': 'verbose',
        },
        'patients': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'patients.log'),
            'formatter': 'verbose',
        },
        'payments': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'payments.log'),
            'formatter': 'verbose',
        },
        'reviews': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'reviews.log'),
            'formatter': 'verbose',
        },
        'users': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_LOG_DIR, 'users.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'appointments': {
            'handlers': ['appointments'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'authify': {
            'handlers': ['authify'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'clinics': {
            'handlers': ['clinics'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'consultations': {
            'handlers': ['consultations'],
            'level': 'DEBUG',
            'propagate': False,
        },

        'dashboard': {
            'handlers': ['dashboard'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'doctors': {
            'handlers': ['doctors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'patients': {
            'handlers': ['patients'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments': {
            'handlers': ['payments'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'reviews': {
            'handlers': ['reviews'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users': {
            'handlers': ['users'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://20.77.64.229',
    'http://h2.doctor',
    'https://h2.doctor',
    
]

CORS_ALLOW_METHODS = (
    "GET",
    "OPTIONS",
    "POST",
    "HEAD",
    "PUT",
    "DELETE",
    "PATCH",
)

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://20.77.64.229',
    'http://h2.doctor',
    'https://h2.doctor',
]

# Twillio 
ACCOUNT_SID = os.getenv("ACCOUNT_SID")
AUTH_TOKEN = os.getenv("AUTH_TOKEN")
TWILIO_WHATSAPP_NUMBER = os.getenv("TWILIO_WHATSAPP_NUMBER")

CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_BROKER_URL = 'redis://209.38.123.166:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Agora video-call
APP_ID = os.getenv("APP_ID")
APP_CERTIFICATE = os.getenv("APP_CERTIFICATE")