# Generated by Django 4.2.5 on 2024-12-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_generated_summary", models.TextField(blank=True, null=True)),
                ("human_verified_summary", models.TextField(blank=True, null=True)),
                ("translated_languages", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("translated_languages", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
