# Generated by Django 4.2.5 on 2024-12-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
        ("appointments", "0001_initial"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
            ),
        ),
        migrations.AddField(
            model_name="consultationsummary",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.appointment",
            ),
        ),
    ]
