# Generated by Django 4.2.5 on 2025-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="content",
            new_name="additional_instruction",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="translated_languages",
            new_name="medicines",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="file",
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
