# Generated by Django 4.2.5 on 2025-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0003_rename_content_prescription_additional_instruction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="prescritpion/"),
        ),
    ]
