# Generated by Django 4.2.5 on 2025-04-11 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0057_alter_bookedappointment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultations", "0004_prescription_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.bookedappointment",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "Doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="prescription/"),
        ),
    ]
