# Generated by Django 4.2.5 on 2025-04-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0060_remove_invitation_benefit_invitation_benefit_type"),
        ("patients", "0011_alter_patient_show_email_alter_patient_show_phone"),
        ("consultations", "0005_alter_prescription_appointment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.TextField(blank=True, null=True)),
                ("translated_text", models.TextField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.bookedappointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.prescription",
                    ),
                ),
            ],
        ),
    ]
