# Generated by Django 4.2.5 on 2025-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0006_consultationreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationreport",
            name="consultation_report",
            field=models.FileField(
                blank=True, null=True, upload_to="consultation_report/"
            ),
        ),
    ]
