# Generated by Django 4.2.5 on 2025-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0007_consultationreport_consultation_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultationreport",
            old_name="translated_text",
            new_name="doctor_translated_text",
        ),
        migrations.AddField(
            model_name="consultationreport",
            name="patient_translated_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
