# Generated by Django 4.2.5 on 2025-01-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_reply_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["created_at"]},
        ),
    ]
