# Generated by Django 4.2.5 on 2025-01-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_reply_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="reply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_replies",
                to="reviews.reply",
            ),
        ),
    ]
