# Generated by Django 4.2.5 on 2025-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_remove_review_reply_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
