# Generated by Django 4.2.5 on 2025-05-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0061_doctor_stripe_link"),
        ("reviews", "0004_review_is_deleted_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.bookedappointment",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
