# Generated by Django 4.2.5 on 2025-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_reply_is_approved_review_appointment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
