# Generated by Django 4.2.5 on 2025-01-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_remove_doctornotes_patient"),
        ("patients", "0002_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Archived", "Archived"),
                ],
                max_length=20,
            ),
        ),
    ]
