# Generated by Django 4.2.5 on 2024-12-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=255)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("treatment_details", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Resolved", "Resolved")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chronic_conditions", models.TextField(blank=True, null=True)),
                ("current_medication", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                (
                    "health_documents",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fav_clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinics.clinic",
                    ),
                ),
            ],
        ),
    ]
