# Generated by Django 4.2.5 on 2025-03-07 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.RenameField(
            model_name="medicalhistory",
            old_name="notes",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="diagnosis_date",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="status",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="treatment_details",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="current_medication",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="health_documents",
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="medical_documents/"
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_documents",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AllergyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="allergy_documents/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("medicine_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_documents",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergy Document",
                "verbose_name_plural": "Allergy Documents",
            },
        ),
    ]
