# Generated by Django 4.2.5 on 2025-03-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0005_alter_clinic_address_and_more"),
        ("doctors", "0031_alter_bookedappointment_doctor_availableslot_and_more"),
        ("patients", "0003_alter_patient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="fav_clinic",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="fav_doc",
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_status", models.BooleanField(default=False)),
                ("clinic_status", models.BooleanField(default=False)),
                (
                    "fav_clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorite_clinics",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "fav_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorite_patients",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
