# Generated by Django 4.2.5 on 2025-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_familymember_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalhistory",
            name="condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="diagnosis_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
