# Generated by Django 4.2.5 on 2025-03-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_medicalhistory_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="member_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
