# Generated by Django 4.2.5 on 2025-03-28 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0008_reminder_reminder_unique_reminder_per_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalhistory",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="allergydocument",
            name="description",
        ),
        migrations.RemoveField(
            model_name="allergydocument",
            name="file",
        ),
        migrations.RemoveField(
            model_name="allergydocument",
            name="medicine_name",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="diagnosis_date",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="file",
        ),
        migrations.RemoveField(
            model_name="medicalhistory",
            name="notes",
        ),
        migrations.AddField(
            model_name="allergydocument",
            name="date",
            field=models.DateField(
                null=True, validators=[patients.models.validate_past_date]
            ),
        ),
        migrations.AddField(
            model_name="allergydocument",
            name="document_link",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="allergydocument",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="date",
            field=models.DateField(
                null=True, validators=[patients.models.validate_past_date]
            ),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="document_link",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="allergydocument",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergy_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="medicalhistory",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
