# Generated by Django 4.2.5 on 2025-03-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_rename_title_medicalhistory_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardMedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="medical_documents/"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("condition", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("diagnosis_date", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_documents",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
