# Generated by Django 4.2.5 on 2025-04-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0010_dashboardmedicalhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="show_phone",
            field=models.BooleanField(default=True),
        ),
    ]
