# Generated by Django 4.2.5 on 2024-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=255)),
                ("qualifications", models.TextField(blank=True, null=True)),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("available_dates", models.JSONField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
