# Generated by Django 4.2.5 on 2024-12-29 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0003_doctornotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctornotes",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "Doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes_as_doctor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="doctornotes",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "Patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes_as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
