# Generated by Django 4.2.5 on 2025-01-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctornotes_doctor_alter_doctornotes_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctornotes",
            name="patient",
        ),
    ]
