# Generated by Django 4.2.5 on 2025-01-25 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0006_referral_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned consultation"),
                            ("Urgent", "Urgent call"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        help_text="Comma-separated days, e.g., Mon,Fri,Sat",
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
