# Generated by Django 4.2.5 on 2025-01-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0007_appointmentmanagement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="redeemed",
            new_name="is_used",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="invited_user_email",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="points",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="registry_link",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="users_invited",
        ),
        migrations.AddField(
            model_name="referral",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="invited_users_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="referral",
            name="referral_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
