# Generated by Django 4.2.5 on 2025-01-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0007_appointmentmanagement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("planned", "Planned Consultation"),
                            ("urgent", "Urgent Call"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "session_length",
                    models.IntegerField(
                        choices=[(15, "15 minutes"), (30, "30 minutes")]
                    ),
                ),
                ("buffer_time", models.DurationField(blank=True, null=True)),
                (
                    "planned_fee_per_15_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "urgent_fee_per_15_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
            ],
        ),
    ]
