# Generated by Django 4.2.5 on 2025-01-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0008_consultationsettings"),
        ("doctors", "0008_rename_redeemed_invitation_is_used_and_more"),
    ]

    operations = []
