# Generated by Django 4.2.5 on 2025-01-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0009_merge_20250130_1635"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultationsettings",
            old_name="planned_fee_per_15_min",
            new_name="planned_fee",
        ),
        migrations.RenameField(
            model_name="consultationsettings",
            old_name="session_length",
            new_name="planned_session_length",
        ),
        migrations.RenameField(
            model_name="consultationsettings",
            old_name="urgent_fee_per_15_min",
            new_name="urgent_fee",
        ),
        migrations.RemoveField(
            model_name="consultationsettings",
            name="session_type",
        ),
        migrations.AddField(
            model_name="consultationsettings",
            name="planned_session",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultationsettings",
            name="urgent_session",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="consultationsettings",
            name="urgent_session_length",
            field=models.IntegerField(
                choices=[(15, "15 minutes"), (30, "30 minutes")], default=1
            ),
            preserve_default=False,
        ),
    ]
