# Generated by Django 4.2.5 on 2025-01-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "doctors",
            "0010_rename_planned_fee_per_15_min_consultationsettings_planned_fee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationsettings",
            name="planned_session_length",
            field=models.IntegerField(
                blank=True, choices=[(15, "15 minutes"), (30, "30 minutes")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="consultationsettings",
            name="urgent_session_length",
            field=models.IntegerField(
                blank=True, choices=[(15, "15 minutes"), (30, "30 minutes")], null=True
            ),
        ),
    ]
