# Generated by Django 4.2.5 on 2025-01-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0011_alter_consultationsettings_planned_session_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="invitation_code",
        ),
        migrations.RemoveField(
            model_name="invitation",
            name="is_used",
        ),
        migrations.AddField(
            model_name="referral",
            name="referral_use",
            field=models.BooleanField(default=False),
        ),
    ]
