# Generated by Django 4.2.5 on 2025-01-31 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0013_userpreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReschedulePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_reschedule", models.BooleanField(default=False)),
                ("max_reschedules", models.PositiveIntegerField(blank=True, null=True)),
                ("reschedule_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reschedule_time_range",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
