# Generated by Django 4.2.5 on 2025-02-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0015_cancellationpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoShowPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned", models.CharField(blank=True, max_length=50, null=True)),
                ("urgent", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "waiting_time_planned",
                    models.CharField(
                        blank=True,
                        help_text="Waiting time for planned cases (e.g., 15 minutes)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "waiting_time_urgent",
                    models.CharField(
                        blank=True,
                        help_text="Waiting time for urgent cases (e.g., 30 minutes)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_show_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
