# Generated by Django 4.2.5 on 2025-02-03 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0016_noshowpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_reminders", models.BooleanField(default=True)),
                ("patient_messages", models.BooleanField(default=True)),
                ("other_important_updates", models.BooleanField(default=True)),
                ("email", models.BooleanField(default=True)),
                ("whatsapp", models.BooleanField(default=True)),
                ("platform_messenger", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
