# Generated by Django 4.2.5 on 2025-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0018_twofactorauthmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="first_appointment",
            field=models.BooleanField(default=False),
        ),
    ]
