# Generated by Django 4.2.5 on 2025-02-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0019_invitation_first_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctornotes",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
            ),
        ),
        migrations.AlterField(
            model_name="reschedulepolicy",
            name="reschedule_days",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
