# Generated by Django 4.2.5 on 2025-02-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0022_membership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="invited_by",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="referral_use",
        ),
    ]
