# Generated by Django 4.2.5 on 2025-02-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0024_twofactormethod_alter_twofactorauthentication_method"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TwoFactorAuthentication",
        ),
        migrations.DeleteModel(
            name="TwoFactorMethod",
        ),
    ]
