# Generated by Django 4.2.5 on 2025-02-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0025_delete_twofactorauthentication_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DoctorNotes",
        ),
    ]
