# Generated by Django 4.2.5 on 2025-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0027_bookedappointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Rescheduled", "Rescheduled"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
