# Generated by Django 4.2.5 on 2025-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0028_bookedappointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointment",
            name="date",
            field=models.DateField(default="2025-03-05"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookedappointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
