# Generated by Django 4.2.5 on 2025-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0029_bookedappointment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
