# Generated by Django 4.2.5 on 2025-03-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0030_bookedappointment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to="doctors.doctor",
            ),
        ),
        migrations.CreateModel(
            name="AvailableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("time_slot", models.CharField(max_length=20)),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bookedappointment",
            name="appointment_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.availableslot",
            ),
        ),
    ]
