# Generated by Django 4.2.5 on 2025-03-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0031_alter_bookedappointment_doctor_availableslot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availableslot",
            name="slot_type",
            field=models.CharField(
                blank=True,
                choices=[("Planned", "Planned"), ("Urgent", "Urgent")],
                max_length=10,
            ),
        ),
    ]
