# Generated by Django 4.2.5 on 2025-03-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0032_availableslot_slot_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationSessionAndFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_session",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "urgent_session",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "planned_session_length",
                    models.IntegerField(
                        blank=True,
                        choices=[(15, "15 minutes"), (30, "30 minutes")],
                        null=True,
                    ),
                ),
                (
                    "urgent_session_length",
                    models.IntegerField(
                        blank=True,
                        choices=[(15, "15 minutes"), (30, "30 minutes")],
                        null=True,
                    ),
                ),
                ("buffer_time", models.DurationField(blank=True, null=True)),
                (
                    "planned_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "urgent_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
            ],
        ),
    ]
