# Generated by Django 4.2.5 on 2025-03-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0033_consultationsessionandfee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentmanagement",
            name="user",
        ),
        migrations.AddField(
            model_name="appointmentmanagement",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_preferences",
                to="doctors.doctor",
            ),
        ),
    ]
