# Generated by Django 4.2.5 on 2025-03-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0034_remove_appointmentmanagement_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_type",
                    models.CharField(
                        blank=True,
                        choices=[("Planned", "Planned"), ("Urgent", "Urgent")],
                        max_length=10,
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bookedappointment",
            name="appointment_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.slot",
            ),
        ),
        migrations.DeleteModel(
            name="AvailableSlot",
        ),
    ]
