# Generated by Django 4.2.5 on 2025-03-16 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_medicalhistory_condition_and_more"),
        ("appointments", "0002_appointment_doctor_appointment_patient_and_more"),
        ("payments", "0005_transaction"),
        ("doctors", "0036_doctorschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientBookAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule", models.JSONField(default=dict)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[("Planned", "Planned"), ("Urgent", "Urgent")],
                        max_length=20,
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
            ],
        ),
    ]
