# Generated by Django 4.2.5 on 2025-03-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0038_alter_slot_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="appointment_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.slot",
            ),
        ),
    ]
