# Generated by Django 4.2.5 on 2025-03-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0039_alter_bookedappointment_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookedappointment",
            name="appointment_status",
        ),
        migrations.DeleteModel(
            name="Slot",
        ),
    ]
