# Generated by Django 4.2.5 on 2025-03-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_medicalhistory_condition_and_more"),
        ("doctors", "0040_remove_bookedappointment_appointment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="patientbookappointment",
            name="patient",
            field=models.IntegerField(
                default=0, help_text="Consider patient as User id"
            ),
            preserve_default=False,
        ),
    ]
