# Generated by Django 4.2.5 on 2025-03-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_medicalhistory_condition_and_more"),
        ("doctors", "0041_alter_bookedappointment_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="patient",
            field=models.IntegerField(help_text="Consider patient as User id"),
        ),
        migrations.AlterField(
            model_name="patientbookappointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
    ]
