# Generated by Django 4.2.5 on 2025-03-20 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0042_alter_bookedappointment_patient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorschedule",
            name="doctor",
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
