# Generated by Django 4.2.5 on 2025-03-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0043_remove_doctorschedule_doctor_doctorschedule_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="doctor",
            field=models.IntegerField(help_text="Consider patient as User id"),
        ),
    ]
