# Generated by Django 4.2.5 on 2025-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0045_alter_bookedappointment_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
