# Generated by Django 4.2.5 on 2025-03-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0046_alter_bookedappointment_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
