# Generated by Django 4.2.5 on 2025-03-31 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0049_bookedappointment_reshceduled_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookedappointment",
            name="reshceduled_by",
        ),
        migrations.AddField(
            model_name="bookedappointment",
            name="rescheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
