# Generated by Django 4.2.5 on 2025-03-31 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0050_remove_bookedappointment_reshceduled_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(default="")),
                (
                    "attachment_file",
                    models.FileField(
                        upload_to="media_digest_documents/",
                        validators=[
                            doctors.models.validate_video_extension,
                            doctors.models.validate_video_size,
                        ],
                    ),
                ),
                (
                    "user_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_digest_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
