# Generated by Django 4.2.5 on 2025-04-01 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0051_mediadigest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licencecertificate",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="licencecertificate",
            name="attachment_name",
        ),
        migrations.RemoveField(
            model_name="licencecertificate",
            name="document",
        ),
        migrations.AddField(
            model_name="licencecertificate",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachment/"),
        ),
        migrations.AddField(
            model_name="licencecertificate",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licencecertificate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licencecertificate",
            name="name",
            field=models.CharField(default="Untitled", max_length=250),
        ),
        migrations.AlterField(
            model_name="licencecertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
