# Generated by Django 4.2.5 on 2025-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0052_rename_uploaded_at_licencecertificate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencecertificate",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="Licence_Certificate/attachment/"
            ),
        ),
    ]
