# Generated by Django 4.2.5 on 2025-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0053_alter_licencecertificate_attachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licencecertificate",
            old_name="is_verified",
            new_name="is_delete",
        ),
        migrations.AddField(
            model_name="licencecertificate",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licencecertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
                null=True,
            ),
        ),
    ]
