# Generated by Django 4.2.5 on 2025-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0054_rename_is_verified_licencecertificate_is_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="planned_hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="doctor",
            name="urgent_hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
