# Generated by Django 4.2.5 on 2025-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0056_bookedappointment_amount_doctorwallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Rescheduled", "Rescheduled"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
