# Generated by Django 4.2.5 on 2025-04-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0057_alter_bookedappointment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
