# Generated by Django 4.2.5 on 2025-04-22 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0058_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="benefit",
            field=models.CharField(
                choices=[
                    ("discount", "Discount on consultation"),
                    ("free", "Free consultation"),
                    ("premium", "Access to premium for 24 hours"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitation_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="is_redeemed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_as",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
