# Generated by Django 4.2.5 on 2025-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0059_invitation_benefit_invitation_invitation_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="benefit",
        ),
        migrations.AddField(
            model_name="invitation",
            name="benefit_type",
            field=models.CharField(
                choices=[
                    ("discount", "Discount on consultation"),
                    ("free", "Free consultation"),
                    ("premium", "Access to premium for 24 hours"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
