# Generated by Django 4.2.5 on 2025-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0060_remove_invitation_benefit_invitation_benefit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="stripe_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
