# Generated by Django 4.2.5 on 2025-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0062_slot_weekdays_slotsweekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointment",
            name="start_datetime_utc",
            field=models.DateTimeField(
                blank=True, help_text="Appointment start time in UTC", null=True
            ),
        ),
    ]
