# Generated by Django 4.2.5 on 2025-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0063_bookedappointment_start_datetime_utc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookedappointment",
            name="start_datetime_utc",
        ),
        migrations.AddField(
            model_name="bookedappointment",
            name="slot_start_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
