# Generated by Django 4.2.5 on 2025-06-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0064_remove_bookedappointment_start_datetime_utc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="stripe_link_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
