# Generated by Django 4.2.5 on 2025-06-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0065_doctor_stripe_link_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedappointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                    ("Transect", "Transect"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookedappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Confirmed", "Confirmed"),
                    ("Rescheduled", "Rescheduled"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
