# Generated by Django 4.2.5 on 2025-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0066_alter_bookedappointment_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookedappointment",
            name="charge_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookedappointment",
            name="payment_intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
