# Generated by Django 4.2.5 on 2025-10-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0067_bookedappointment_charge_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "government_id",
                    models.FileField(blank=True, null=True, upload_to="government_id/"),
                ),
                (
                    "proof_of_address",
                    models.FileField(
                        blank=True, null=True, upload_to="proof_of_address/"
                    ),
                ),
                (
                    "cv_resume",
                    models.FileField(blank=True, null=True, upload_to="cv_resume/"),
                ),
                (
                    "medical_license",
                    models.FileField(
                        blank=True, null=True, upload_to="medical_license/"
                    ),
                ),
                (
                    "clinic_affiliation",
                    models.FileField(
                        blank=True, null=True, upload_to="clinic_affiliation/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
